/* File: PlotRMS.C (ROOT macro).
 *
 * Author: Miguel Del Ben Galdiano (miguel.galdiano@gmail.com).
 * Date of creation : February 5 2020.
 * Last Update      : February 5 2020.
 *
 * Summary of File:
 *
 *    This macro takes the f90 histograms generated from a data set, a electron recoil (ER) only Monte Carlo (MC)
 *    simulation and a nuclear recoil (NR) only MC simulation. Each of the histograms considers a specific bin of
 *    the total charge, each of the bins with the same size, up to a maximum value. For each of the histograms, the
 *    macro takes the value of the root mean square (RMS), along its error, and saves it to the correct variable.
 *    Finally, the RMS are ploted as a function of total charge and the resulting plot is saved as a png and pdf.
 *
 *    IMPORTANT NOTE: This code assumes that the histograms were generated by utilizing the CreateF90Histograms
 *    macro, and therefore follows the logic of the directories defined there. If your histograms were not generated
 *    by the aforementioned macro, please make sure to do so, or else the code will not run.
 */

#include <array>
#include <cmath>
#include <iostream>
#include <stdlib.h>

#include <TCanvas.h>
#include <TFile.h>
#include <TGraph.h>
#include <TH1.h>
#include <TKey.h>
#include <TLegend.h>
#include <TMath.h>
#include <TObject.h>
#include <TString.h>
#include <TSystem.h>
#include <TTree.h>

/* TFile* CheckFile( TString path_name )
 *
 * Summary of CheckFile function:
 *
 *    The CheckFile function checks if a given file already exists and returns this information to the user.
 *    If the file exists, CheckFile returns it. If not, it creates it and then returns it.
 *
 * Parameters   : path_name >> The name of the desired file.
 *
 * Return value : TFile* file.
 */
TFile* CheckFile( TString path_name ){

  if (gSystem -> AccessPathName(path_name)) {
    std::cout << "The " << path_name << " file does not exist. Creating it..." << std::endl;
  } else {
    std::cout << "Opening file: " << path_name << std::endl;
  }

  TFile *file = new TFile(path_name, "UPDATE");
  if ( !(file -> IsOpen()) ) { std::cout << "Unable to open file." << std::endl;}

  return file;
}

// Function to generate mean F90 v Charge Plots
void GenerateMeanF90vChargePlot( TGraph* data_graph, TGraph* mc_graph, int ERorNR, TDirectory* directory, Double_t x_size, Double_t y_size ){

  TCanvas* mean_canvas = new TCanvas( Form("%s_mean_canvas", (ERorNR == 0)?"er":"nr"), Form("%s_mean_canvas", (ERorNR == 0)?"er":"nr"), x_size, y_size);

  TMultiGraph* mean_multigraph = new TMultiGraph();
  mean_multigraph -> Add(data_graph); mean_multigraph -> Add(mc_graph);

  mean_multigraph -> SetTitle( Form("Data and MC f90 Mean Comparision (1220, %s); Charge (PE); Mean", (ERorNR == 0)?"ER":"NR") );
  mean_multigraph -> SetName( Form("f90MeanxCharge_total_%s_both", (ERorNR == 0)?"er":"nr") );
  mean_multigraph -> Draw("ALP");

  TLegend* er_mean_legend = new TLegend(0.674067, 0.776657, 0.924319, 0.926513);
  er_mean_legend -> AddEntry( data_graph, "Data",        "lep" );
  er_mean_legend -> AddEntry( mc_graph,   "Monte Carlo", "lep" );
  er_mean_legend -> Draw();

  directory -> WriteObject( mean_multigraph, Form("f90MeanxCharge_total_%s_both", (ERorNR == 0)?"er":"nr"), "OverWrite");

  mean_canvas -> SaveAs( Form("plots/1220/Study of Monte Carlo/Mean and RMS/f90 Mean v Charge (%s).pdf", (ERorNR == 0)?"ER":"NR") );
  mean_canvas -> SaveAs( Form("plots/1220/Study of Monte Carlo/Mean and RMS/f90 Mean v Charge (%s).png", (ERorNR == 0)?"ER":"NR") );

}

/* TGraphErrors* GraphDiff( TGraphErrors* graph1, TGraphErrors* graph2, Int_t option = 0 )
 *
 * Summary of GraphDiff function:
 *
 *    The GraphDiff function takes two TGraphErrors objects and returns a third TGraphErrors object containing
 *    the difference between them. The two graphs given to the function must have the same number of points for
 *    the function to run without errors. The user has three options when it comes to the output: option 1
 *    returns the absolute difference, option 2 calculates the difference relative to the first graph and option
 *    2 returns the difference relative to the second graph.
 *
 * Parameters   : graph1 >> first graph.
 *                graph2 >> second graph.
 *                option >> determines the type of differnce to be calculated. Defaults to absolute difference.
 *
 * Return value : TGraphErrors* graph_diff.
 */
TGraphErrors* GraphDiff( TGraphErrors* graph1, TGraphErrors* graph2, Int_t option ){
  Int_t n_points1 = graph1 -> GetN();   Int_t n_points2 = graph2 -> GetN();

  if ( n_points1 != n_points2 ) { exit(EXIT_FAILURE); }

  Double_t* y1_value = graph1 -> GetY();    Double_t* y1_error = graph1 -> GetEY();
  Double_t* y2_value = graph2 -> GetY();    Double_t* y2_error = graph2 -> GetEY();

  Double_t* x_value  = graph1 -> GetX();    Double_t* x_error   = graph1 ->GetEX();

  Double_t y_diff[n_points1];
  Double_t y_diff_error[n_points1];

  Double_t abs_diff = 0;
  Double_t abs_diff_error = 0;

  for ( Int_t i = 0; i < n_points1; i++ ) {
    if ( option == 0 ) {

      y_diff[i] = TMath::Abs( y1_value[i] - y2_value[i] );
      y_diff_error[i] = TMath::Sqrt( pow(y1_error[i], 2) + pow(y2_error[i], 2) );

    } else if ( option == 1 ) {

      abs_diff = TMath::Abs( y1_value[i] - y2_value[i] );
      abs_diff_error = TMath::Sqrt( pow(y1_error[i], 2) + pow(y2_error[i], 2) );

      y_diff[i] = abs_diff / y1_value[i];
      y_diff_error[i] = y_diff[i] * TMath::Sqrt( pow( (abs_diff_error/abs_diff), 2 ) + pow( (y1_error[i]/y1_value[i]), 2 ) );

    } else if ( option == 2 ) {

      abs_diff = TMath::Abs( y1_value[i] - y2_value[i] );
      abs_diff_error = TMath::Sqrt( pow(y1_error[i], 2) + pow(y2_error[i], 2) );

      y_diff[i] = abs_diff / y2_value[i];
      y_diff_error[i] = y_diff[i] * TMath::Sqrt( pow( (abs_diff_error/abs_diff), 2 ) + pow( (y2_error[i]/y2_value[i]), 2 ) );
    }
  }

  TGraphErrors* graph_diff = new TGraphErrors(n_points1, x_value, y_diff, x_error, y_diff_error);
  return graph_diff;
}

/* TDirectory* MakeDirectory( const char* dir_name, const char* dir_title )
 *
 * Summary of MakeDirectory function:
 *
 *    The MakeDirectory function checks wether a given directory currently exists. If it does, it returns a
 *    pointer to it. If it doesn't, the function creates the directory with the given name in the current
 *    path and returns a pointer to it.
 *
 * Parameters   : dir_name  >> name of the desired directory.
 *                dir_title >> title of the directory, for bookeeping purpouses.
 *
 * Return value : TDirectory* directory.
 */
TDirectory* MakeDirectory( const char* dir_name, const char* dir_title ){

  TDirectory *directory = gDirectory -> GetDirectory(dir_name);
  if (!directory) directory = gDirectory -> mkdir(dir_name, dir_title);

  return directory;
}

/* Int_t NumberOfHistograms ( TDirectory* directory )
 *
 * Summary of NumberofHistograms function:
 *
 *    The NumberofHistograms function counts the number of one dimenstional histograms in a given directory
 *    by interating over all objects located in it and checking which inherit from TH1. It then returns the
 *    number of 1D histograms in the directory.
 *
 * Parameters   : directory >> a pointer to the the directory where the histograms are located.
 *
 * Return value : Int_t number_of_histograms.
 */
Int_t NumberOfHistograms( TDirectory* directory ){

  Int_t number_of_histograms = 0;
  TKey* key;

  TIter next( (TList *)directory -> GetListOfKeys() );

  while ( (key = (TKey *)next()) ) {
    TClass *object_class = gROOT -> GetClass( key->GetClassName() );
    if ( object_class -> InheritsFrom("TH1") ) {
      number_of_histograms++;
    }
  }

  return number_of_histograms;
}

/* TGraphErrors WriteGraph (TDirectory* directory, Int_t n, Double_t* x, Double_t* y, Double_t* ex = 0, Double_t* ey = 0,
                            const char* title = "", const char* name = "graph", Int_t ms = 22)
 *
 * Summary of WriteGraph function:
 *
 *    The WriteGraph function takes the necessary parameters to construct a TGraphErrors object and does. It
 *    can also take some parameters to determine the name, title and marker style of the resulting graph. The
 *    code than writes the graph to the given directory and returns it.
 *
 * Parameters   : directory       >> where to write the graph.
 *                title           >> title of the graph ("TITLE; XAXIS; YAXIS").
 *                name            >> name of the graph.
 *                ms              >> indicates the MarkerStyle to be used.
 *                mc              >> indicates the MarkerColor to be used.
 *                n, x, y, ex, ey >> necessary parameters to construct a TGraphErros object.
 *
 * Return Value : TGraphErros* graph
 */
TGraphErrors* WriteGraph( TDirectory* directory, Int_t n, Double_t* x, Double_t* y, Double_t* ex = 0, Double_t* ey = 0,
                          const char* title = "", const char* name = "graph", Int_t ms = 22, Int_t mc = 1){

  TGraphErrors* graph = new TGraphErrors(n, x, y, ex, ey);
  graph -> SetTitle(title);
  graph -> SetName(name);
  graph -> SetMarkerStyle(ms);
  graph -> SetMarkerColor(mc);
  graph -> SetMarkerSize(1.5);
  graph -> SetLineColor(mc);
  graph -> GetXaxis() -> SetRangeUser(-50., 1100.);
  graph -> GetXaxis() -> SetTitle("Charge (PE)");
  graph -> GetYaxis() -> SetTitle("RMS");

  directory -> WriteObject(graph, name, "OverWrite");

  return graph;
}

// **************************************************** PlotRMS() MACRO **************************************************** //
void PlotRMS(int run){

  TString file_name = Form("hist_%d.root", run);
  TFile* hist_file = CheckFile(file_name);

  // --------------------- CREATING NECESSARY DIRECTORIES ---------------------- //
  hist_file -> cd();
  TDirectory* RMS_analysis_dir   = MakeDirectory("RMS_analysis", "RMS_analysis");
  TDirectory* histograms_dir     = MakeDirectory("histograms", "histograms");

  RMS_analysis_dir -> cd();
  TDirectory* graphs_dir         = MakeDirectory("graphs", "graphs");

  histograms_dir -> cd();
  TDirectory* f90_histograms_dir = MakeDirectory("f90", "f90");

  f90_histograms_dir -> cd();
  TDirectory* data_dir           = MakeDirectory("data", "data");
  TDirectory* monte_carlo_dir    = MakeDirectory("monte_carlo", "monte_carlo");

  data_dir -> cd();
  TDirectory* da_both_dir         = MakeDirectory("both","both");
  TDirectory* da_er_dir           = MakeDirectory("ER","ER");
  TDirectory* da_nr_dir           = MakeDirectory("NR","NR");

  monte_carlo_dir -> cd();
  TDirectory* mc_er_dir           = MakeDirectory("ER","ER");
  TDirectory* mc_nr_dir           = MakeDirectory("NR","NR");
  // --------------------------------------------------------------------------- //

  Int_t number_of_histograms = NumberOfHistograms(da_both_dir);

  Double_t RMS_da_er     [number_of_histograms];      Double_t RMS_da_nr     [number_of_histograms];
  Double_t RMSerr_da_er  [number_of_histograms];      Double_t RMSerr_da_nr  [number_of_histograms];
  Double_t MEAN_da_er    [number_of_histograms];      Double_t MEAN_da_nr    [number_of_histograms];
  Double_t MEANerr_da_er [number_of_histograms];      Double_t MEANerr_da_nr [number_of_histograms];

  Double_t RMS_mc_er     [number_of_histograms];      Double_t RMS_mc_nr     [number_of_histograms];
  Double_t RMSerr_mc_er  [number_of_histograms];      Double_t RMSerr_mc_nr  [number_of_histograms];
  Double_t MEAN_mc_er    [number_of_histograms];      Double_t MEAN_mc_nr    [number_of_histograms];
  Double_t MEANerr_mc_er [number_of_histograms];      Double_t MEANerr_mc_nr [number_of_histograms];

  Double_t charge_total[number_of_histograms];

  TH1F* htemp = 0;

  for ( int i = 0; i < number_of_histograms; i++ ){

    htemp = (TH1F *)da_er_dir -> Get( Form("f90_histogram_er_%d", i+1) );
    RMS_da_er[i]  = htemp -> GetRMS();   RMSerr_da_er[i]  = htemp -> GetRMSError();
    MEAN_da_er[i] = htemp -> GetMean();  MEANerr_da_er[i] = htemp -> GetMeanError();

    htemp = (TH1F *)da_nr_dir -> Get( Form("f90_histogram_nr_%d", i+1) );
    RMS_da_nr[i]  = htemp -> GetRMS();   RMSerr_da_nr[i]  = htemp -> GetRMSError();
    MEAN_da_nr[i] = htemp -> GetMean();  MEANerr_da_nr[i] = htemp -> GetMeanError();

    htemp = (TH1F *)mc_er_dir -> Get( Form("f90_histogram_mcer_%d", i+1) );
    RMS_mc_er[i]  = htemp -> GetRMS();   RMSerr_mc_er[i]  = htemp -> GetRMSError();
    MEAN_mc_er[i] = htemp -> GetMean();  MEANerr_mc_er[i] = htemp -> GetMeanError();

    htemp = (TH1F *)mc_nr_dir -> Get( Form("f90_histogram_mcnr_%d", i+1) );
    RMS_mc_nr[i]  = htemp -> GetRMS();   RMSerr_mc_nr[i]  = htemp -> GetRMSError();
    MEAN_mc_nr[i] = htemp -> GetMean();  MEANerr_mc_nr[i] = htemp -> GetMeanError();

    charge_total[i] = 20*(i+1) - 10;
  }

  TGraphErrors* da_er_rms_graph  = WriteGraph( graphs_dir, number_of_histograms, charge_total, RMS_da_er,  0, RMSerr_da_er,
                                              "RMS of f90 Histograms (ER)",     "f90RMSxCharge_total_er",    22, 40);
  TGraphErrors* da_er_mean_graph = WriteGraph( graphs_dir, number_of_histograms, charge_total, MEAN_da_er, 0, MEANerr_da_er,
                                              "Mean of f90 Histograms (ER)",    "f90MeanxCharge_total_er",   22, 40);
  TGraphErrors* da_nr_rms_graph  = WriteGraph( graphs_dir, number_of_histograms, charge_total, RMS_da_nr,  0, RMSerr_da_nr,
                                              "RMS of f90 Histograms (NR)",     "f90RMSxCharge_total_nr",    23, 40);
  TGraphErrors* da_nr_mean_graph = WriteGraph( graphs_dir, number_of_histograms, charge_total, MEAN_da_nr, 0, MEANerr_da_nr,
                                              "Mean of f90 Histograms (NR)",    "f90MeanxCharge_total_nr",   23, 40);
  TGraphErrors* mc_er_rms_graph  = WriteGraph( graphs_dir, number_of_histograms, charge_total, RMS_mc_er,  0, RMSerr_mc_er,
                                              "RMS of f90 Histograms (MC ER)",  "f90RMSxCharge_total_mcer",  22, 30);
  TGraphErrors* mc_er_mean_graph = WriteGraph( graphs_dir, number_of_histograms, charge_total, MEAN_mc_er, 0, MEANerr_mc_er,
                                              "Mean of f90 Histograms (MC ER)", "f90MeanxCharge_total_mcer", 22, 30);
  TGraphErrors* mc_nr_rms_graph  = WriteGraph( graphs_dir, number_of_histograms,  charge_total, RMS_mc_nr, 0, RMSerr_mc_nr,
                                              "RMS of f90 Histograms (MC NR)",  "f90RMSxCharge_total_mcnr",  23, 30);
  TGraphErrors* mc_nr_mean_graph = WriteGraph( graphs_dir, number_of_histograms, charge_total, MEAN_mc_nr, 0, MEANerr_mc_nr,
                                              "Mean of f90 Histograms (MC NR)", "f90MeanxCharge_total_mcnr", 23, 30);

  // ******************************************* CONSTRUCTING THE DESIRED PLOTS ******************************************* //

  Double_t y_size = 1000.;
  Double_t x_size = 1.61803398875 * y_size;

  // Mean x Charge Total Plots --------------------------------------------------------------------------- //

  GenerateMeanF90vChargePlot( da_er_mean_graph, mc_er_mean_graph, 0, graphs_dir, x_size, y_size );

  GenerateMeanF90vChargePlot( da_nr_mean_graph, mc_nr_mean_graph, 1, graphs_dir, x_size, y_size );


  /*TCanvas* nr_mean_canvas = new TCanvas("nr_mean_canvas", "nr_mean_canvas", x_size, y_size);

  TMultiGraph* nr_mean_multigraph = new TMultiGraph();
  nr_mean_multigraph -> Add(da_nr_mean_graph); nr_mean_multigraph -> Add(mc_nr_mean_graph);

  nr_mean_multigraph -> SetTitle("Data and MC f90 Mean Comparision (1220, NR); Charge (PE); Mean");
  nr_mean_multigraph -> SetName("f90MeanxCharge_total_nr_both");
  nr_mean_multigraph -> Draw("ALP");

  TLegend* nr_mean_legend = new TLegend(0.674067, 0.776657, 0.924319, 0.926513);
  nr_mean_legend -> AddEntry( da_nr_mean_graph, "Data", "lep" );
  nr_mean_legend -> AddEntry( mc_nr_mean_graph, "Monte Carlo", "lep" );
  nr_mean_legend -> Draw();

  graphs_dir -> WriteObject ( nr_mean_multigraph, "f90MeanxCharge_total_nr_both", "OverWrite" );*/

  // Relative Difference of Mean x Charge Total Plots ---------------------------------------------------- //

  TCanvas* er_mean_diff_canvas = new TCanvas("er_mean_diff_canvas", "er_mean_diff_canvas", x_size, y_size);

  TGraphErrors* er_mean_diff_graph = GraphDiff( da_er_mean_graph, mc_er_mean_graph, 1 );
  er_mean_diff_graph -> SetTitle("Relative Difference of MC and Data f90 Mean (1220, ER); Charge(PE); Difference");
  er_mean_diff_graph -> SetName("f90Mean_diffxCharge_total_er");

  er_mean_diff_graph -> SetMarkerStyle(22);
  er_mean_diff_graph -> SetMarkerColor(46);
  er_mean_diff_graph -> SetMarkerSize(1.5);
  er_mean_diff_graph -> SetLineColor(46);

  er_mean_diff_graph -> Draw();

  graphs_dir -> WriteObject( er_mean_diff_graph, "f90Mean_diffxCharge_total_er", "OverWrite" );


  TCanvas* nr_mean_diff_canvas = new TCanvas("nr_mean_diff_canvas", "nr_mean_diff_canvas", x_size, y_size);

  TGraphErrors* nr_mean_diff_graph = GraphDiff( da_nr_mean_graph, mc_nr_mean_graph, 1 );
  nr_mean_diff_graph -> SetTitle("Relative Difference of MC and Data f90 Mean (1220, NR); Charge(PE); Difference");
  nr_mean_diff_graph -> SetName("f90Mean_diffxCharge_total_nr");

  nr_mean_diff_graph -> SetMarkerStyle(23);
  nr_mean_diff_graph -> SetMarkerColor(46);
  er_mean_diff_graph -> SetMarkerSize(1.5);
  nr_mean_diff_graph -> SetLineColor(46);

  nr_mean_diff_graph -> Draw();

  graphs_dir -> WriteObject( nr_mean_diff_graph, "f90Mean_diffxCharge_total_nr", "OverWrite" );

  // RMS x Charge Total Plots ---------------------------------------------------------------------------- //

  TCanvas* er_rms_canvas = new TCanvas("er_rms_canvas", "er_rms_canvas", x_size, y_size);

  TMultiGraph* er_rms_multigraph = new TMultiGraph();
  er_rms_multigraph -> Add(da_er_rms_graph); er_rms_multigraph -> Add(mc_er_rms_graph);

  er_rms_multigraph -> SetTitle("Data and MC f90 RMS Comparision (1220, ER); Charge (PE); RMS");
  er_rms_multigraph -> SetName("f90RMSxCharge_total_er_both");
  er_rms_multigraph -> Draw("ALP");

  TLegend* er_rms_legend = new TLegend(0.674067, 0.776657, 0.924319, 0.926513);
  er_rms_legend -> AddEntry( da_er_rms_graph, "Data ", "lep" );
  er_rms_legend -> AddEntry( mc_er_rms_graph, "Monte Carlo", "lep" );
  er_rms_legend -> Draw();

  graphs_dir -> WriteObject( er_rms_multigraph, "f90RMSxCharge_total_er_both", "OverWrite" );


  TCanvas* nr_rms_canvas = new TCanvas("nr_rms_canvas", "nr_rms_canvas", x_size, y_size);

  TMultiGraph* nr_rms_multigraph = new TMultiGraph();
  nr_rms_multigraph -> Add(da_nr_rms_graph); nr_rms_multigraph -> Add(mc_nr_rms_graph);

  nr_rms_multigraph -> SetTitle("Data and MC f90 RMS Comparision (1220, NR); Charge (PE); RMS");
  nr_rms_multigraph -> SetName("f90RMSxCharge_total_nr_both");
  nr_rms_multigraph -> Draw("ALP");

  TLegend* nr_rms_legend = new TLegend(0.674067, 0.776657, 0.924319, 0.926513);
  nr_rms_legend -> AddEntry( da_nr_rms_graph, "Data", "lep" );
  nr_rms_legend -> AddEntry( mc_nr_rms_graph, "Monte Carlo", "lep" );
  nr_rms_legend -> Draw();

  graphs_dir -> WriteObject( nr_rms_multigraph, "f90RMSxCharge_total_nr_both", "OverWrite" );

  // Relative Difference of RMS x Charge Total Plots ----------------------------------------------------- //

  TCanvas* er_rms_diff_canvas = new TCanvas("er_rms_diff_canvas", "er_rms_diff_canvas", x_size, y_size);

  TGraphErrors* er_rms_diff_graph = GraphDiff( da_er_rms_graph, mc_er_rms_graph, 1 );
  er_rms_diff_graph -> SetTitle("Relative Difference of MC and Data f90 RMS (1220, ER); Charge(PE); Difference");
  er_rms_diff_graph -> SetName("f90RMS_diffxCharge_total_er");

  er_rms_diff_graph -> SetMarkerStyle(22);
  er_rms_diff_graph -> SetMarkerColor(46);
  er_rms_diff_graph -> SetMarkerSize(1.5);
  er_rms_diff_graph -> SetLineColor(46);

  er_rms_diff_graph -> Draw();

  graphs_dir -> WriteObject( er_rms_diff_graph, "f90RMS_diffxCharge_total_er", "OverWrite" );


  TCanvas* nr_rms_diff_canvas = new TCanvas("nr_rms_diff_canvas", "nr_rms_diff_canvas", x_size, y_size);

  TGraphErrors* nr_rms_diff_graph = GraphDiff( da_nr_rms_graph, mc_nr_rms_graph, 1 );
  nr_rms_diff_graph -> SetTitle("Relative Difference of MC and Data f90 RMS (1220, NR); Charge(PE); Difference");
  nr_rms_diff_graph -> SetName("f90RMS_diffxCharge_total_nr");

  nr_rms_diff_graph -> SetMarkerStyle(23);
  nr_rms_diff_graph -> SetMarkerColor(46);
  er_rms_diff_graph -> SetMarkerSize(1.5);
  nr_rms_diff_graph -> SetLineColor(46);

  nr_rms_diff_graph -> Draw();

  graphs_dir -> WriteObject( nr_rms_diff_graph, "f90RMS_diffxCharge_total_nr", "OverWrite" );

  // Saving All Plots Generated -------------------------------------------------------------------------_ //

  er_rms_canvas       -> SaveAs("plots/1220/Study of Monte Carlo/Mean and RMS/f90 RMS v Charge (ER).pdf");
  er_rms_canvas       -> SaveAs("plots/1220/Study of Monte Carlo/Mean and RMS/f90 RMS v Charge (ER).png");
  nr_rms_canvas       -> SaveAs("plots/1220/Study of Monte Carlo/Mean and RMS/f90 RMS v Charge (NR).pdf");
  nr_rms_canvas       -> SaveAs("plots/1220/Study of Monte Carlo/Mean and RMS/f90 RMS v Charge (NR).png");

  er_rms_diff_canvas  -> SaveAs ("plots/1220/Study of Monte Carlo/Mean and RMS/Relative f90 RMS Diff. v Charge (ER).pdf");
  er_rms_diff_canvas  -> SaveAs ("plots/1220/Study of Monte Carlo/Mean and RMS/Relative f90 RMS Diff. v Charge (ER).png");
  nr_rms_diff_canvas  -> SaveAs ("plots/1220/Study of Monte Carlo/Mean and RMS/Relative f90 RMS Diff. v Charge (NR).pdf");
  nr_rms_diff_canvas  -> SaveAs ("plots/1220/Study of Monte Carlo/Mean and RMS/Relative f90 RMS Diff. v Charge (NR).png");

  //nr_mean_canvas      -> SaveAs("plots/1220/Study of Monte Carlo/Mean and RMS/f90 Mean v Charge (NR).pdf");
  //nr_mean_canvas      -> SaveAs("plots/1220/Study of Monte Carlo/Mean and RMS/f90 Mean v Charge (NR).png");

  er_mean_diff_canvas -> SaveAs ("plots/1220/Study of Monte Carlo/Mean and RMS/Relative f90 Mean Diff. v Charge (ER).pdf");
  er_mean_diff_canvas -> SaveAs ("plots/1220/Study of Monte Carlo/Mean and RMS/Relative f90 Mean Diff. v Charge (ER).png");
  nr_mean_diff_canvas -> SaveAs ("plots/1220/Study of Monte Carlo/Mean and RMS/Relative f90 Mean Diff. v Charge (NR).pdf");
  nr_mean_diff_canvas -> SaveAs ("plots/1220/Study of Monte Carlo/Mean and RMS/Relative f90 Mean Diff. v Charge (NR).png");
}
